# Generated by Django 2.2.7 on 2020-02-25 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('state', models.IntegerField(choices=[(1, 'Inserita'), (2, 'Presa in carico'), (3, 'Risolta'), (4, 'Riaperta'), (5, 'Da verificare')], default=1)),
                ('priority', models.IntegerField(choices=[(1, 'Bassa'), (2, 'Media'), (3, 'Alta')], default=2)),
                ('expired_date', models.DateField(blank=True, null=True)),
                ('assignee', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
