# Generated by Django 2.2.7 on 2019-11-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Bassa'), (2, 'Media'), (3, 'Alta')], default=2),
        ),
        migrations.AddField(
            model_name='issue',
            name='state',
            field=models.IntegerField(choices=[(1, 'Inserita'), (2, 'Presa in carico'), (3, 'Risolta'), (4, 'Riaperta'), (5, 'Da verificare')], default=1),
        ),
    ]
