# Generated by Django 2.2.7 on 2019-11-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20191118_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='issue.User'),
        ),
    ]
