# Generated by Django 2.2.7 on 2020-01-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_issue_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
